name: exopipe-prt
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - setuptools
  - wheel
  - meson-python
  - ninja
  - numpy
  - scipy
  - bottleneck
  - matplotlib
  - astropy
  - pyyaml
  - h5py
  - dynesty
  - emcee
  - corner
  - pip:
      - petitRADTRANS[retrieval]
